name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      user:
        type: choice
        options:
          - nada
          - nicolas
      class:
        type: choice
        options:
          - "Cardio HIIT"
          - "Cardio Max"
          - "Intensif"
      day:
        type: choice
        options:
          - Dimanche
          - Lundi
          - Mardi
          - Mercredi
          - Jeudi
          - Vendredi
          - Samedi
      time:
        type: string
      location:
        type: string
      request_token:
        type: string
env:
  INPUT_USER: ${{ github.event.inputs.user }}
  INPUT_CLASS: ${{ github.event.inputs.class }}
  INPUT_LOCATION: ${{ github.event.inputs.location }}
  INPUT_DAY: ${{ github.event.inputs.day }}
  INPUT_TIME: ${{ github.event.inputs.time }}
  INPUT_REQUEST_TOKEN: ${{ github.event.inputs.request_token }}
  USER_NADA_LOGIN: ${{ secrets.USER_NADA_LOGIN }}
  USER_NADA_PASSWORD: ${{ secrets.USER_NADA_PASSWORD }}
  USER_NICOLAS_LOGIN: ${{ secrets.USER_NICOLAS_LOGIN }}
  USER_NICOLAS_PASSWORD: ${{ secrets.USER_NICOLAS_PASSWORD }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
